version: '3'

services:
  server:
    container_name: mvc-server
    build:
      context: ./app
      dockerfile: ../docker/server/dev/Dockerfile #memo: dockerfileはcontextからの相対パス
    tty: true
    restart: always
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ./app:/go/src/github.com/mahiro72/go-mvc-server
    depends_on:
      - db
  db:
    container_name: mvc-db
    build:
      context: ./app/db
      dockerfile: ../../docker/db/dev/Dockerfile
    tty: true
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/dev/mysql:/var/lib/mysql
      - ./docker/db/dev/initdb.d:/docker-entrypoint-initdb.d
